import { blog1, blog2, blog3 } from "../assets/LandingPage";

export const blogsConstant = [
  {
    id: 1,
    img: blog1,
    tittle: "Waterfalls In Sri Lanka: ",
    subtitle: " Explore The Beauty",
    date: "9th March, 2023",
    location: "Bhutan, South Asia",
  },
  {
    id: 2,
    img: blog2,
    tittle: "Waterfalls In Sri Lanka:",
    subtitle: " Explore The Beauty",
    date: "9th March, 2023",
    location: "Bhutan, South Asia",
  },
  {
    id: 3,
    img: blog3,
    tittle: "Waterfalls In Sri Lanka:",
    subtitle: " Explore The Beauty",
    date: "9th March, 2023",
    location: "Bhutan, South Asia",
  },
  {
    id: 4,
    img: blog1,
    tittle: "Waterfalls In Sri Lanka: ",
    subtitle: " Explore The Beauty",
    date: "9th March, 2023",
    location: "Bhutan, South Asia",
  },
  {
    id: 5,
    img: blog2,
    tittle: "Waterfalls In Sri Lanka:",
    subtitle: " Explore The Beauty",
    date: "9th March, 2023",
    location: "Bhutan, South Asia",
  },
  {
    id: 6,
    img: blog3,
    tittle: "Waterfalls In Sri Lanka:",
    subtitle: " Explore The Beauty",
    date: "9th March, 2023",
    location: "Bhutan, South Asia",
  },
  {
    id: 7,
    img: blog1,
    tittle: "Waterfalls In Sri Lanka: ",
    subtitle: " Explore The Beauty",
    date: "9th March, 2023",
    location: "Bhutan, South Asia",
  },
  {
    id: 8,
    img: blog2,
    tittle: "Waterfalls In Sri Lanka:",
    subtitle: " Explore The Beauty",
    date: "9th March, 2023",
    location: "Bhutan, South Asia",
  },
  {
    id: 9,
    img: blog3,
    tittle: "Waterfalls In Sri Lanka:",
    subtitle: " Explore The Beauty",
    date: "9th March, 2023",
    location: "Bhutan, South Asia",
  },
];
