import { u2, u3 } from "../Images";
import { c1 } from "../assets/LandingPage";

export const array = [
  {
    id: 1,
    heading: "Explore Bhutan’s Magic ! ",
    location: "Bhutan, South Asia",
    date: "June 2, June 3.. 5+",
    time: "7D/6N",
    person: "$450 / Person",
    rateing: "4.4",
    img: c1,
  },
  {
    id: 2,
    heading: "Explore Bhutan’s Magic ! ",
    location: "Bhutan, South Asia",
    date: "June 2, June 3.. 5+",
    time: "7D/6N",
    person: "$450 / Person",
    rateing: "4.4",
    img: u2,
  },
  {
    id: 3,
    heading: "Explore Bhutan’s Magic ! ",
    location: "Bhutan, South Asia",
    date: "June 2, June 3.. 5+",
    time: "7D/6N",
    person: "$450 / Person",
    rateing: "4.4",
    img: u3,
  },
  {
    id: 4,
    heading: "Explore Bhutan’s Magic ! ",
    location: "Bhutan, South Asia",
    date: "June 2, June 3.. 5+",
    time: "7D/6N",
    person: "$450 / Person",
    rateing: "4.4",
    img: c1,
  },
  {
    id: 5,
    heading: "Explore Bhutan’s Magic ! ",
    location: "Bhutan, South Asia",
    date: "June 2, June 3.. 5+",
    time: "7D/6N",
    person: "$450 / Person",
    rateing: "4.4",
    img: u2,
  },
  {
    id: 6,
    heading: "Explore Bhutan’s Magic ! ",
    location: "Bhutan, South Asia",
    date: "June 2, June 3.. 5+",
    time: "7D/6N",
    person: "$450 / Person",
    rateing: "4.4",
    img: u3,
  },
];
