"use client";

import logo_img from "./assets/logo.png";
import logo3_img from "./assets/logo3.png";
import logof_img from "./assets/logof.png";
import footerbg_img from "./assets/footerbg.png";
import footermbg_img from "./assets/footermbg.png";
import blogsbg_img from "./assets/blogsbg.png";
import img1_img from "./assets/img1.png";
import eye_img from "./assets/eye.png";
import rocket_img from "./assets/rocket.png";
import t1_img from "./assets/t1.png";
import t2_img from "./assets/t2.png";
import t3_img from "./assets/t3.png";
import t4_img from "./assets/t4.png";
import t5_img from "./assets/t5.png";
import t6_img from "./assets/t6.png";
import gallary_img from "./assets/gallary.png";
import facebook_img from "./assets/facebook.png";
import signUpbg_img from "./assets/signUpbg.png";
import u2_img from "./assets/u2.png";
import u3_img from "./assets/u3.png";
import image_img from "./assets/image.png";
import line_img from "./assets/line.png";
import payment_img from "./assets/payment.png";
import allpkgbg_img from "./assets/allpkgbg.png";
import email_img from "./assets/email.png";
import location_img from "./assets/location.png";
import clock_img from "./assets/clock.png";
import calender_img from "./assets/calender.png";
import group_img from "./assets/Group.png";
import ps1_img from "./assets/ps1.png";
import pf1_img from "./assets/pf1.png";
import ps2_img from "./assets/ps2.png";
import currency_img from "./assets/currency.png";
import cardab_img from "./assets/LandingPage/cardab.png";
import enquirbg_img from "./assets/enquirbg.png";
import comma_img from "./assets/coma.png";
import hostbg_img from "./assets/hostbg.png";
import hostFlag_img from "./assets/hostFlag.png";
import aboutBannerbg_img from "./assets/aboutBannerbg.png";
import persent_img from "./assets/persent.png";

export const logo = logo_img?.src || logo_img;
export const logo3 = logo3_img?.src || logo3_img;
export const logof = logof_img?.src || logof_img;
export const footerbg = footerbg_img?.src || footerbg_img;
export const footermbg = footermbg_img?.src || footermbg_img;
export const blogsbg = blogsbg_img?.src || blogsbg_img;
export const img1 = img1_img?.src || img1_img;
export const eye = eye_img?.src || eye_img;
export const rocket = rocket_img?.src || rocket_img;
export const t1 = t1_img?.src || t1_img;
export const t2 = t2_img?.src || t2_img;
export const t3 = t3_img?.src || t3_img;
export const t4 = t4_img?.src || t4_img;
export const t5 = t5_img?.src || t5_img;
export const t6 = t6_img?.src || t6_img;
export const gallary = gallary_img?.src || gallary_img;
export const facebook = facebook_img?.src || facebook_img;
export const signUpbg = signUpbg_img?.src || signUpbg_img;
export const u2 = u2_img?.src || u2_img;
export const u3 = u3_img?.src || u3_img;
export const image = image_img?.src || image_img;
export const line = line_img?.src || line_img;
export const payment = payment_img?.src || payment_img;
export const allpkgbg = allpkgbg_img?.src || allpkgbg_img;
export const email = email_img?.src || email_img;
export const location = location_img?.src || location_img;
export const clock = clock_img?.src || clock_img;
export const calender = calender_img?.src || calender_img;
export const group = group_img?.src || group_img;
export const ps1 = ps1_img?.src || ps1_img;
export const pf1 = pf1_img?.src || pf1_img;
export const ps2 = ps2_img?.src || ps2_img;
export const currency = currency_img?.src || currency_img;
export const cardab = cardab_img?.src || cardab_img;
export const enquirbg = enquirbg_img?.src || enquirbg_img;
export const comma = comma_img?.src || comma_img;
export const hostbg = hostbg_img?.src || hostbg_img;
export const hostFlag = hostFlag_img?.src || hostFlag_img;
export const aboutBannerbg = aboutBannerbg_img?.src || aboutBannerbg_img;
export const persent = persent_img?.src || persent_img;
